param(
    [string]$RunId = "w048-excel-multithread-variant-001",
    [string]$OutputRoot = "docs/test-runs/excel-cycles"
)
$ErrorActionPreference = "Stop"
function New-Dir([string]$Path){ if(-not(Test-Path -LiteralPath $Path)){New-Item -ItemType Directory -Force -Path $Path|Out-Null} }
function Write-Json($Value,[string]$Path,[int]$Depth=30){$enc=New-Object System.Text.UTF8Encoding($false);[System.IO.File]::WriteAllText((Resolve-Path -LiteralPath (Split-Path -Parent $Path)).Path+"\"+(Split-Path -Leaf $Path),($Value|ConvertTo-Json -Depth $Depth),$enc)}
function Snap($Sheet,[string[]]$Cells){$rows=@();foreach($c in $Cells){$r=$Sheet.Range($c);$f=$null;$v=$null;$t=$null;try{$f=[string]$r.Formula}catch{};try{$v=$r.Value2}catch{};try{$t=[string]$r.Text}catch{};$rows+=[ordered]@{cell="Sheet1!$c";formula=$f;value2=$v;text=$t}};$rows}
function Run-Steps($Excel,$Sheet,$Steps){foreach($step in $Steps){switch($step.op){"set_value"{if($step.value -is [string]){$Sheet.Range($step.target).Value2=[string]$step.value}else{$Sheet.Range($step.target).Value2=[double]$step.value};try{$Excel.CalculateFullRebuild()}catch{}}"set_formula"{$Sheet.Range($step.target).Formula=$step.formula;try{$Excel.CalculateFullRebuild()}catch{}}"calculate_full_rebuild"{$Excel.CalculateFullRebuild()}"calculate"{$Excel.Calculate()}}}}
$runRoot=Join-Path $OutputRoot $RunId;New-Dir $runRoot;New-Dir (Join-Path $runRoot "probes")
$probes=@(
 [ordered]@{id="excel_iter_two_node_order_001";cells=@("A1","B1");iteration=$true;max_iterations=1;max_change=0.001;steps=@(@{op="set_value";target="A1";value=1},@{op="set_value";target="B1";value=10},@{op="calculate_full_rebuild"},@{op="set_formula";target="A1";formula="=B1+1"},@{op="set_formula";target="B1";formula="=A1*2"});expected=@{A1="11";B1="22"}},
 [ordered]@{id="excel_iter_three_node_order_001";cells=@("A1","B1","C1");iteration=$true;max_iterations=2;max_change=0.001;steps=@(@{op="set_value";target="A1";value=1},@{op="set_value";target="B1";value=10},@{op="set_value";target="C1";value=100},@{op="calculate_full_rebuild"},@{op="set_formula";target="A1";formula="=B1+1"},@{op="set_formula";target="B1";formula="=C1+1"},@{op="set_formula";target="C1";formula="=A1+1"});expected=@{A1="102";B1="101";C1="103"}},
 [ordered]@{id="excel_iter_fraction_precision_001";cells=@("A1");iteration=$true;max_iterations=20;max_change=0.000001;steps=@(@{op="set_value";target="A1";value=0},@{op="calculate_full_rebuild"},@{op="set_formula";target="A1";formula="=(A1+1)/3"});expected=@{A1="0.333333333333333"}},
 [ordered]@{id="excel_ctro_indirect_iterative_self_001";cells=@("A1","B1");iteration=$true;max_iterations=5;max_change=0.001;steps=@(@{op="set_value";target="B1";value="A1"},@{op="set_value";target="A1";value=0},@{op="calculate_full_rebuild"},@{op="set_formula";target="A1";formula="=INDIRECT(B1)+1"});expected=@{A1="1";B1="A1"}}
)
$excel=$null;$observations=@();$environment=[ordered]@{}
try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false;$excel.AskToUpdateLinks=$false;$build=$null;try{$build=[string]$excel.Build}catch{};$mtBefore=$null;$threads=$null;try{$mtBefore=[bool]$excel.MultiThreadedCalculation.Enabled}catch{};try{$excel.MultiThreadedCalculation.Enabled=$true}catch{};try{$threads=[int]$excel.MultiThreadedCalculation.ThreadCount}catch{};$mtAfter=$null;try{$mtAfter=[bool]$excel.MultiThreadedCalculation.Enabled}catch{};$environment=[ordered]@{excel_version=[string]$excel.Version;build=$build;platform="Windows";locale=[System.Globalization.CultureInfo]::CurrentCulture.Name;probe_runner="scripts/run-w048-excel-multithread-variant-probes.ps1";observation_time_utc=(Get-Date).ToUniversalTime().ToString("o");multi_threaded_before=$mtBefore;multi_threaded_after=$mtAfter;thread_count=$threads}
 foreach($probe in $probes){$probeDir=Join-Path (Join-Path $runRoot "probes") $probe.id;New-Dir $probeDir;$wb=$excel.Workbooks.Add();$closed=$false;try{$ws=$wb.Worksheets.Item(1);$ws.Name="Sheet1";try{$excel.Iteration=[bool]$probe.iteration}catch{};try{$excel.MaxIterations=[int]$probe.max_iterations}catch{};try{$excel.MaxChange=[double]$probe.max_change}catch{};Run-Steps $excel $ws $probe.steps;$snapshot=Snap $ws $probe.cells;$obs=[ordered]@{probe_id=$probe.id;status="observed";iteration_profile=[ordered]@{enabled=[bool]$probe.iteration;max_iterations=[int]$probe.max_iterations;max_change=[double]$probe.max_change};multi_threaded_enabled=$mtAfter;thread_count=$threads;cell_results=$snapshot;expected=$probe.expected};Write-Json $obs (Join-Path $probeDir "observation.json");$observations+=$obs;$wb.Close($false);$closed=$true}finally{if(-not$closed){try{$wb.Close($false)}catch{}};try{[System.Runtime.InteropServices.Marshal]::ReleaseComObject($wb)|Out-Null}catch{}}}
}finally{if($null-ne$excel){try{$excel.Quit()}catch{};[System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null};[GC]::Collect();[GC]::WaitForPendingFinalizers()}
$summary=[ordered]@{schema_version="oxcalc.w048.excel_multithread_variant_probe.v1";run_id=$RunId;status="observed";environment=$environment;observation_count=@($observations).Count;observations=$observations;disposition="Multithread calculation variant packet for declared falsification fixtures."}
Write-Json $environment (Join-Path $runRoot "environment.json");Write-Json $summary (Join-Path $runRoot "observation.json");Write-Output "Wrote W048 Excel multithread variant packet to $runRoot"
